tasks:
  - init: |
      docker-compose pull
  - command: |
      export PUBLIC_IP=127.0.0.1
      docker-compose up
ports:
  # Kafka Manager
  - port: 28044
    onOpen: open-preview
    visibility: public

  # AKHQ
  - port: 28042
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker    