tasks:
  - init: |
      docker-compose pull
  - command: |
      export PUBLIC_IP=127.0.0.1
      docker-compose up
  - name: Open readme
    command: gp await port 23000 1>/dev/null && gp open README.md
  - name: Open readme
    command: gp await port 23000 1>/dev/null && gp open lab1-firstStepsWithKafka/readme.md
ports:

  # AKHQ
  - port: 28042
    onOpen: open-preview
    visibility: public

  # Kafka Broker, Zookeeper 2188 
  # 9993, 9994, 9992
  - port: 28044
    onOpen: open-preview
    visibility: public
  - port: 2188
    onOpen: ignore
  - port: 9092
    onOpen: ignore
  - port: 9093
    onOpen: ignore
  - port: 9094
    onOpen: ignore
  - port: 9994
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker    