tasks:
  - init: |
      mkdir /workspace/dapr
      wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | DAPR_INSTALL_DIR="/workspace/dapr" /bin/bash 
      docker-compose pull
      # open the readme document for the first lab in VS code; note: thanks to the configuration in .vscode/settings.json, the document opens in markdown preview nide
      gp open lab4-exploring-dapr/readme.md
      # pull MySQL container instance - to experiment with MySQL as statestore instead of Redis
      docker pull mysql:latest
      # run MySQL container instance - to experiment with MySQL as statestore instead of Redis
      docker run --name dapr-mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:latest
      alias dapr="/workspace/dapr/dapr"
  - name: Initialize Dapr
    command: |
      # initialize dapr - see https://docs.dapr.io/getting-started/install-dapr-selfhost/ 
      sleep 10s &&
      /workspace/dapr/dapr uninstall &&   # init fails if already done; however, after workspace restart, part of the initialization is lost - hence the uninstall / re-init
      /workspace/dapr/dapr init &&
      /workspace/dapr/dapr --version
      # add alias for dapr to .bashrc so every new terminal session has it set
      echo 'alias dapr="/workspace/dapr/dapr"' >> ~/.bashrc
      alias dapr="/workspace/dapr/dapr"
  - command: |
      docker start dapr-mysql
      alias dapr="/workspace/dapr/dapr"
  - command: |
      export PUBLIC_IP=127.0.0.1
      docker-compose up
      gp env KAFKAJS_NO_PARTITIONER_WARNING=1
      alias dapr="/workspace/dapr/dapr"

ports:

  # AKHQ
  - port: 28042
    onOpen: open-preview
    visibility: public

  # Node
  - port: 3000
    onOpen: ignore
    visibility: public
  - port: 3001
    onOpen: ignore
    visibility: public
  - port: 3002
    onOpen: ignore
    visibility: public


  # Kafka Brokers, Zookeeper 
  - port: 2188
    onOpen: ignore
  - port: 9092
    onOpen: ignore
  - port: 9093
    onOpen: ignore
  - port: 9094
    onOpen: ignore
  - port: 2181
    onOpen: ignore
  - port: 9992
    onOpen: ignore
  - port: 9993
    onOpen: ignore
  - port: 9994
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker    