tasks:
  - init: |
      docker-compose pull
      gp open lab1-firstStepsWithKafka/readme.md
  - command: |
      export PUBLIC_IP=127.0.0.1
      docker-compose up
ports:

  # AKHQ
  - port: 28042
    onOpen: open-preview
    visibility: public

  # Kafka Brokers, Zookeeper 
  - port: 2188
    onOpen: ignore
  - port: 9092
    onOpen: ignore
  - port: 9093
    onOpen: ignore
  - port: 9094
    onOpen: ignore
  - port: 2181
    onOpen: ignore
  - port: 9992
    onOpen: ignore
  - port: 9993
    onOpen: ignore
  - port: 9994
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker    