tasks:
  - init: |
      docker-compose pull
      # open the readme document for the first lab in VS code; note: thanks to the configuration in .vscode/settings.json, the document opens in markdown preview nide
      gp open lab1-firstStepsWithKafka/readme.md
  - command: |
      export PUBLIC_IP=127.0.0.1
      docker-compose up
      gp env KAFKAJS_NO_PARTITIONER_WARNING=1

ports:

  # AKHQ
  - port: 28042
    onOpen: open-preview
    visibility: public

  # Node
  - port: 3000
    onOpen: ignore
    visibility: public
  - port: 3001
    onOpen: ignore
    visibility: public
  - port: 3002
    onOpen: ignore
    visibility: public


  # Kafka Brokers, Zookeeper 
  - port: 2188
    onOpen: ignore
  - port: 9092
    onOpen: ignore
  - port: 9093
    onOpen: ignore
  - port: 9094
    onOpen: ignore
  - port: 2181
    onOpen: ignore
  - port: 9992
    onOpen: ignore
  - port: 9993
    onOpen: ignore
  - port: 9994
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker    