apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
  - name: brokers # Required. Kafka broker connection setting
    value: "localhost:29092,localhost:29093,localhost:29094"
  - name: authType # Required.
    value: "none"
  - name: authRequired
    value: "false"